#!/bin/bash

OME=OvenMediaEngine
BIN_DIR="../src/bin/DEBUG"
PKG_DIR="tmp/$OME"
OME_TGZ="$OME.tar.gz"
OME_BINS="$BIN_DIR/$OME conf dep edge_server origin_server install"

[ "x$1" == "xclean" ] && rm -rf $OME $OME_TGZ test_origin test_edge && exit

rm -rf $PKG_DIR && mkdir -p $PKG_DIR
cp -rf $OME_BINS $PKG_DIR

(cd tmp && tar cvzf ../$OME_TGZ $OME)
rm -rf tmp

./local_test

(cd test_origin/OvenMediaEngine;./install origin_server)

(cd test_edge/OvenMediaEngine;./install edge_server "192.168.0.225")
